name: Run daily GitHub streak

on:
  push:
    branches:
    - master

  pull_request:
    types:
      - opened
      - closed
      - synchronize

  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  deploy:
    name: Run day streak cron
    runs-on: ubuntu-latest
    environment: Node

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node typescript environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install project's dependencies
        run: npm install

      - name: Build TypeScript project
        run: npm run build

      - name: Run the project
        env:
          EMAIL_USER: ${{secrets.GMAIL_SERVICE_EMAIL}}
          EMAIL_PASS: ${{secrets.GMAIL_SERVICE_PASSWORD}}
          EMAIL_RECP: ${{secrets.EMAIL_RECEPIENT}}
          EMAIL_RECP_NAME=: ${{secrets.EMAIL_RECEPIENT_NAME}}
          EMAIL_RECP_DEFAULT: ${{secrets.DEFAULT_EMAIL_RECEPIENT}}
          SUBJECT: ${{secrets.EMAIL_SUBJECT}}
          DIRECTORY_NAME: ${{secrets.OUTPUT_MARKDOWN_DIRECTORY}}
          FILE_NAME: ${{secrets.MARKDOWN_FILE}}
          GITHUB_REPOSITORY_URL: ${{secrets.REPO_URL}}

        run: npm start

      - name: Configure Git
        env:
          GITHUB_EMAIL: ${{secrets.USER_GITHUB_EMAIL}}
          GITHUB_USER: ${{secrets.USER_NAME}}

        run: |
          git config user.name "${GITHUB_USER}"
          git config user.email "${GITHUB_EMAIL}"

      - name: Commit the changes to GitHub
        env:
          GH_PAT: ${{secrets.TOKEN}}
          GITHUB_REPO: ${{github.repository}}

        run: |
          echo "::debug::REPO=${GITHUB_REPO}"
          echo "::debug::TOKEN=${GH_PAT}"
          git add  "./directory/${{secrets.MARKDOWN_FILE}}.md"
          git commit -m "Update with the latest markdown file"
          git push https://x-access-token:${GH_PAT}@github.com/${GITHUB_REPO}.git HEAD:master

      - name: Close workflow at this point
        if: always()
        env:
          GH_PAT: ${{secrets.TOKEN}}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${GH_PAT}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel
